ClothingStore/Models/Products/ProductListViewModel.cs
namespace ClothingStore.Model.Products
{
    public class ProductListViewModel
    {
        public IEnumerable<ProductViewModel>? Products { get; set; }
    }
}

ClothingStore/Models/Products/ProductViewModel.cs
namespace ClothingStore.Model.Products
{
    public class ProductViewModel
    {
        public Guid Id { get; set; }
        public string? Name { get; set; }
        public int Count { get; set; }
        public float Price { get; set; }
        public string? TitleImagePath { get; set; }
        public string? Brand { get; set; }
        public string? ClothingType { get; set; }
        public string? SizeName { get; set; }
    }
}

ClothingStore/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClothingStore.Domain;
using ClothingStore.Domain.Entities;
using ClothingStore.Model.Products;
using ClothingStore.Models.Price;
using ClothingStore.Models.Brands;
using ClothingStore.Models.Sizes;
using ClothingStore.Models.ClothingType;

namespace ClothingStore.Controllers
{
    public class ProductsController : Controller
    {
        private readonly AppDbContext _context;

        public ProductsController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            List<Product> products = await _context.Products.ToListAsync();
            List<ProductViewModel> viewModels = new();
            foreach (Product product in products)
            {
                ProductViewModel model = new()
                { 
                    Id = product.Id,
                    Count = product.Count,
                    Name = product.Name,
                    TitleImagePath = product.TitleImagePath,
                    Brand = product.BrandName,
                    ClothingType = product.ClothingTypeName,
                    Price = product.Price
                };
                viewModels.Add(model);
            }
            return View(new ProductListViewModel {Products = viewModels});
        }
        public async Task<IActionResult> SortByBrand(Guid id)
        {
            if (id != default)
            {
                List<Product>? products = await _context.Products.ToListAsync();
                var sortProducts = from product in products where product.BrandId == id select product;
                List<ProductViewModel> viewModels = new();
                foreach (var model in sortProducts)
                {
                    ProductViewModel viewModel = new()
                    {
                        Id = model.Id,
                        Name = model.Name,
                        Price = model.Price,
                        Brand = model.BrandName,
                        Count = model.Count,
                        TitleImagePath = model.TitleImagePath,
                        ClothingType = model.ClothingTypeName,
                        SizeName = model.SizeName
                    };
                    viewModels.Add(viewModel);
                }
                return View("Index", new ProductListViewModel { Products = viewModels });
            }
            List<Brand> brands = await _context.Brands.ToListAsync();
            List<BrandViewModel> brandList = new();
            foreach (var brand in brands)
            {
                BrandViewModel model = new()
                { 
                    Id = brand.Id,
                    ManufacturerCountry = brand.ManufacturerCountry,
                    Name = brand.Name,
                    TitleImagePath = brand.TitleImagePath
                };
                brandList.Add(model);
            }
            return View(new BrandListViewModel {Brands=brandList });
        }
        public async Task<IActionResult> SortBySize(Guid id)
        {
            if (id != default)
            {
                List<Product>? products = await _context.Products.ToListAsync();
                var sortProducts = from product in products where product.SizeId == id select product;
                List<ProductViewModel> viewModels = new();
                foreach (var model in sortProducts)
                {
                    ProductViewModel viewModel = new()
                    {
                        Id = model.Id,
                        Name = model.Name,
                        Price = model.Price,
                        Brand = model.BrandName,
                        Count = model.Count,
                        TitleImagePath = model.TitleImagePath,
                        ClothingType = model.ClothingTypeName,
                        SizeName = model.SizeName
                    };
                    viewModels.Add(viewModel);
                }
                return View("Index", new ProductListViewModel { Products = viewModels });
            }
            List<Size> sizes = await _context.Sizes.OrderBy(x => x.Name).ToListAsync();
            List<SizeViewModel> sizeList = new();
            foreach (var size in sizes)
            {
                SizeViewModel model = new()
                {
                    Id = size.Id,
                    ChestCircumference = size.ChestCircumference,
                    HipCircumference = size.HipCircumference,
                    WaistCircumference = size.WaistCircumference,
                    Name = size.Name
                };
                sizeList.Add(model);
            }
            return View(new SizeListViewModel { Sizes = sizeList });
        }
        public async Task<IActionResult> SortByPriсe(PriceViewModel price)
        {
            if (price.MaxPrice != default || price.MinPrice != default)
            {
                List<Product>? products = await _context.Products.ToListAsync();
                var sortProducts = from product in products where product.Price > price.MinPrice && product.Price < price.MaxPrice orderby product.Price select product;
                List<ProductViewModel> viewModels = new();
                foreach (var model in sortProducts)
                {
                    ProductViewModel viewModel = new()
                    {
                        Id = model.Id,
                        Name = model.Name,
                        Price = model.Price,
                        Brand = model.BrandName,
                        Count = model.Count,
                        TitleImagePath = model.TitleImagePath,
                        ClothingType = model.ClothingTypeName,
                        SizeName = model.SizeName
                    };
                    viewModels.Add(viewModel);
                }
                return View("Index" ,new ProductListViewModel { Products = viewModels });
            }
            return View();
        }
        public async Task<IActionResult> SortByType(Guid id)
        {
            if (id != default)
            {
                List<Product> products = await _context.Products.ToListAsync();
                var sortProducts = from product in products where product.ClothingTypeId == id select product;
                List<ProductViewModel> viewModels = new();
                foreach (var model in sortProducts)
                {
                    ProductViewModel viewModel = new()
                    {
                        Id = model.Id,
                        Name = model.Name,
                        Price = model.Price,
                        Brand = model.BrandName,
                        Count = model.Count,
                        TitleImagePath = model.TitleImagePath,
                        ClothingType = model.ClothingTypeName,
                        SizeName = model.SizeName
                    };
                    viewModels.Add(viewModel);
                }
                return View("Index", new ProductListViewModel { Products = viewModels });
            }
            List<ClothingType> types = await _context.ClothingTypes.OrderBy(x => x.Name).ToListAsync();
            List<ClothingTypeViewModel> typesViewModel = new();
            foreach (var type in types)
            {
                ClothingTypeViewModel model = new()
                { 
                    Id = type.Id,
                    Name = type.Name
                };
                typesViewModel.Add(model);
            }
            return View(new ClothingTypeListViewModel {ClothingTypes = typesViewModel });
        }
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }
            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,SizeId,BrandId,Count,Price,TitleImagePath")] Product product)
        {
            if (ModelState.IsValid)
            {
                product.Id = Guid.NewGuid();
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,SizeId,BrandId,Count,Price,TitleImagePath")] Product product)
        {
            if (id != product.Id)
            {

ClothingStore/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClothingStore.Domain;
using ClothingStore.Domain.Entities;
using ClothingStore.Models.Sales;
using ClothingStore.TestData.Employees;

namespace ClothingStore.Controllers
{
    public class SalesController : Controller
    {
        private readonly AppDbContext _context;

        public SalesController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            List<Sale> sales = await _context.Sales.ToListAsync();
            List<SaleViewModel> salesViewModel = new();
                foreach (var sale in sales)
                {
                    SaleViewModel model = new()
                    {
                        Id = sale.Id,
                        EmployeeId = sale.EmployeeId,
                        DateOfSale = sale.DateOfSale,
                        Price = sale.Price,
                        ProductId = sale.ProductId,
                        ProductName = sale.ProductName,
                        TitleImagePath = sale.TitleImagePath,
                        EmpolyeeName = sale.EmployeeName
                    };
                salesViewModel.Add(model);
                }
            return View(new SaleListViewModel { Sales = salesViewModel });
        }
        public async Task<IActionResult> Sale(Guid Id)
        {
            Product? product = await _context.Products.FindAsync(Id);
            if (product != null)
            {
                Sale sale = new()
                {
                    ProductId = Id,
                    Price = product.Price,
                    TitleImagePath = product.TitleImagePath,
                    ProductName = product.Name
                };
                _context.Sales.Add(sale);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(SalesController.Index));
            }
            return View();

        }
        public async Task<IActionResult> Delete(Guid Id)
        {
            Sale? sale = await _context.Sales.FindAsync(Id);
            _context.Sales.Remove(sale);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(SalesController.Index));
        }
    }
}

ClothingStore/Views/Products/Create.cshtml
@model ClothingStore.Domain.Entities.Product

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SizeId" class="control-label"></label>
                <input asp-for="SizeId" class="form-control" />
                <span asp-validation-for="SizeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandId" class="control-label"></label>
                <input asp-for="BrandId" class="form-control" />
                <span asp-validation-for="BrandId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Count" class="control-label"></label>
                <input asp-for="Count" class="form-control" />
                <span asp-validation-for="Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TitleImagePath" class="control-label"></label>
                <input asp-for="TitleImagePath" class="form-control" />
                <span asp-validation-for="TitleImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ClothingStore/Views/Products/Delete.cshtml
@model ClothingStore.Domain.Entities.Product

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SizeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SizeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BrandId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BrandId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Count)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Count)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TitleImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TitleImagePath)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ClothingStore/Views/Products/Details.cshtml
@model ClothingStore.Domain.Entities.Product

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SizeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SizeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BrandId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BrandId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Count)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Count)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TitleImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TitleImagePath)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ClothingStore/Views/Products/Edit.cshtml
@model ClothingStore.Domain.Entities.Product

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SizeId" class="control-label"></label>
                <input asp-for="SizeId" class="form-control" />
                <span asp-validation-for="SizeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandId" class="control-label"></label>
                <input asp-for="BrandId" class="form-control" />
                <span asp-validation-for="BrandId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Count" class="control-label"></label>
                <input asp-for="Count" class="form-control" />
                <span asp-validation-for="Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TitleImagePath" class="control-label"></label>
                <input asp-for="TitleImagePath" class="form-control" />
                <span asp-validation-for="TitleImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ClothingStore/Views/Products/Index.cshtml
@model ProductListViewModel
@{
    ViewData["Title"] = "Index";
}



    <div class="sortirovka">
        <h2>Сортировать по: </h2>
            <a class="evenboxinner" asp-controller="Products" asp-action="SortByBrand">Бренду</a>
            <a class="evenboxinner" asp-controller="Products" asp-action="SortBySize">Размеру</a>
            <a class="evenboxinner" asp-controller="Products" asp-action="SortByPriсe">Цене</a>
            <a class="evenboxinner" asp-controller="Products" asp-action="SortByType">Типу</a>
    </div>
<div class="productList">
    @foreach (var entity in Model.Products)
    {
            <div class="produktcard">
                <img src="~/images/@entity.TitleImagePath" alt="">
                <p>@entity.Name</p>
                <p>@entity.Brand</p>
                <p>@entity.Price рублей</p>
                <a asp-area="" asp-controller="Sales" asp-action="Sale" asp-route-id="@entity.Id">
                    <input type="submit" class="evenboxinner" value="SALE">
                </a>
            </div>
    }
</div>

ClothingStore/Views/Products/SortByBrand.cshtml
@model BrandListViewModel
<ul class="sort_blok">
    @foreach (var brand in Model.Brands)
    {
            <li class="brand_blok">
                <div>
                    <a class="evenboxinner" asp-controller="Products" asp-action="SortByBrand" asp-route-id="@brand.Id">@brand.Name</a>
                    <p>@brand.ManufacturerCountry</p>
                </div>
                <img class="brand_img"src="~/images/@brand.TitleImagePath" alt="">
            </li>
    }
</ul>

ClothingStore/Views/Products/SortByPriсe.cshtml
@model PriceViewModel
<form asp-controller="Products" asp-action="SortByPriсe"> 
        <div class="form">
            <h2>Минимальная цена</h2>
            <div class="input-container ic1">
                <input type="number" name="MinPrice" size="5" min="1" max="100000" value="1">
            </div>
            <h2>Максимальная цена</h2>
            <div class="input-container ic2">
                <input type="number" name="MaxPrice" size="5" min="1" max="100000" value="100000">
            </div>
            <input style="display: inline-block;" type="submit" class="evenboxinner" value="Найти">
        </div>
    </form>

ClothingStore/Views/Products/SortBySize.cshtml
@model SizeListViewModel
<ul>
    @foreach (var size in Model.Sizes)
    {
        <li>
            <a class="evenboxinner" asp-controller="Products" asp-action="SortBySize" asp-route-id="@size.Id">@size.Name</a>
            <p>Обхват груди @size.ChestCircumference</p>
            <p>Обхват талии @size.WaistCircumference</p>
            <p>Обхват бёдер @size.HipCircumference</p>
        </li>
    }
</ul>

ClothingStore/Views/Products/SortByType.cshtml
@model ClothingTypeListViewModel
<ul>
    @foreach (var type in Model.ClothingTypes)
    {
        <li>
            <a class="evenboxinner" asp-controller="Products" asp-action="SortByType" asp-route-id="@type.Id">@type.Name</a>
        </li>
    }
</ul>